# Generated by Django 3.1.2 on 2020-10-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgupload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoonizer',
            name='name',
            field=models.CharField(default='Anonymous', max_length=30),
        ),
        migrations.AlterField(
            model_name='cartoonizer',
            name='action',
            field=models.CharField(choices=[('GR', 'grayscale'), ('FD', 'facedetection'), ('ED', 'eyedetection')], default='GR', max_length=2),
        ),
    ]
